export const CREATE_VOUCHER = "CREATE_VOUCHER";
export const RETRIEVE_VOUCHERS = "RETRIEVE_VOUCHERS";
export const RETRIEVE_ONE_VOUCHER = "RETRIEVE_ONE_VOUCHER";
export const UPDATE_VOUCHER = "UPDATE_VOUCHER";
export const DELETE_VOUCHER = "DELETE_VOUCHER";